config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/welcome/contact', to: 'welcome#contact'
  get '/welcome/team', to: 'welcome#team'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  resources :gossips do
    resources :comments
  end

  resources :likes, only: [:index, :new, :create, :destroy]

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: { in: 3..14 }
  validates :content, presence: true, uniqueness: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :join_tag_gossips
  has_many :comments
  has_many :likes, as: :imageable
  has_many :tags, through: :join_tag_gossips
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :check_user_author, only: [:edit, :update, :destroy]
  

  def index
    @all_gossips = Gossip.all
  end

  def show
    @one_gossip = Gossip.find(params[:id].to_i)
  end 

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title:gossip_params["title"],content:gossip_params["content"])
    @gossip.user_id = current_user.id

    if @gossip.save # essaie de sauvegarder en base @gossip
      puts gossip_params["tag_list"]
      gossip_params["tag_list"].drop(1).each do |tag_number|
        JoinTagGossip.create(gossip_id: @gossip.id, tag_id: tag_number)
      end 

      redirect_to gossips_path(success_gossip_create:true) # si ça marche, il redirige vers la page d'index du site
    else
      render 'new' # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end 

  def edit 
    @gossip = Gossip.find(params[:id])
  end 

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(title:params[:title],content:params[:content]) 
      redirect_to gossip_path(params[:id], success_gossip_update:true) 
    else
      render 'edit' 
    end
  end 

  def destroy
    @gossip = Gossip.find(params[:id])

    if @gossip.delete
      redirect_to gossips_path(success_gossip_delete:true) 
    end
  end 

  private
    def gossip_params
      params.require(:gossip).permit(:title, :content, :user_id, :tag_list => [])
    end

    def authenticate_user
      unless current_user
        redirect_to new_session_path(connexion_obligatoire:true)
      end
    end

    def check_user_author
      unless current_user.id == Gossip.find(params[:id].to_i).user.id
        redirect_to gossip_path(params[:id],impossible:true)
      end
    end

end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<html>
  <head>
    <title>Editer un potin</title>
  </head>
  <body>
    <h3>Edites un potin !</h3><br />
    <p>Fais une mise à jour de ton potin via le formulaire ci-dessous : <br>
      <em> Le texte pré-rempli est celui du potin actuel. </em></p>

    <% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à mettre à jour le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-page__form">
      <%= form_tag url_for(action: 'update'), method: "patch" do %>

        <%= label_tag 'Titre du potin :' %>
        <%= text_field_tag 'title', @gossip.title, class:"form-control", required: true %>
        <br /> <br />

        <%= label_tag 'Ton potin :' %>
        <%= text_area_tag 'content', @gossip.content, class:"form-control", required: true %>
        <br /> <br />

        <%= submit_tag "Enregistrer de ton potin !" %> 
      <% end %>
    </div><br /> <br />

  </body>
</html>

app/views/gossips/index.html.erb
<html>
  <head>
    <% if params[:success] %>
      <div class="alert alert-success" role="alert">
        Votre potin a été créé/supprimé avec succès !
      </div>
    <% end %>

    <% if params[:success_login] %>
      <div class="alert alert-success" role="alert">
        Authentification réussie !
      </div>
    <% end %>

    <% if current_user == nil %>
      <h3>Bienvenu.e sur la liste des potins ! </h3>
      
    <% else %>
      <h3>Bienvenu.e <%= current_user.first_name %> sur la liste des potins ! </h3>

    <% end %>
    <p>Nous sommes particulière heureux de te retrouver !</p><br>
  </head>

  <body>

    <p>Pour créer un nouveau potin, <a <%= link_to "cliques ici !", new_gossip_path %></a>

    <p>Voici la liste des potins actuellement disponibles sur notre plateforme :</p><br>

    <% @all_gossips.sort_by{|gossip| gossip.updated_at}.reverse.each do |gossip| %>
      <div class="card">
        <h5 class="card-header">Titre du potin :</u> <%= gossip.title %></h5>
        <div class="card-body">
          <h5 class="card-title">Auteur : <%= gossip.user.first_name %></h5>
          <h5 class="card-title">Nombre de commentaires associés à ce potin : <%= gossip.comments.size %></h5>
          <a class="btn btn-primary" <%= link_to "Lire le potin !", gossip_path(gossip.id) %></a>
        </div>
      </div>
      <br>
    <% end %>

  </body>

</html>

app/views/gossips/new.html.erb
<html>
  <head>
    <title>Créer un potin</title>
  </head>
  <body>
    <h3>Crée un potin !</h3><br />
    <p>Balance ton potin via le formulaire ci-dessous</p>

    <% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @gossip do |form| %>
      <%= form.label :title, "Titre du potin :" %>
      <%= form.text_field :title, class:"form-control", placeholder: "Super Potin !", required: true %>
      <br /> <br />

      <%= form.label :content, "Ton potin :" %>
      <%= form.text_area :content, class:"form-control", placeholder: "La liste des corrections THP est disponible sous l'url ...", required: true %>
      <br /> <br />

      <%= form.collection_check_boxes :tag_list, Tag.all, :id, :title, checked: Tag.all.map(&:id) do |b| %>
        <span>
          <%= b.check_box %>
          <%= b.label %>
        </span>
      <% end %>

      <br /> <br />
      <%= form.submit "Enregistrer de ton potin !", class: "create" %>
    <% end %>

  </body>
</html>

app/views/gossips/show.html.erb
<html>
  <head>
    <h3>Page dédiée au gossip n°<%= params[:id]%></h3><br>

    <% if params[:impossible] %>
      <div class="alert alert-danger" role="alert">
        Impossible de modifier/supprimer un potin que tu n'as pas écrit !
      </div><br>
    <% end %>
  </head>

  <body>
    <div>
      <% if params[:success_gossip_update] %>
        <div class="alert alert-success" role="alert">
          Le potin a été actualisé avec succès !
        </div><br>
      <% end %>

      <% if params[:success_comment_create] %>
        <div class="alert alert-success" role="alert">
          Le commentaire a été créé avec succès !
        </div><br>
      <% end %>

      <% if params[:success_comment_update] %>
        <div class="alert alert-success" role="alert">
          Le commentaire a été actualisé avec succès !
        </div><br>
      <% end %>

      <% if params[:success_comment_delete] %>
        <div class="alert alert-success" role="alert">
          Le commentaire a été supprimé avec succès !
        </div><br>
      <% end %>
    </div>

    <div>
      <p>
        <u>Auteur :</u> <%= @one_gossip.user.first_name %>  <%= @one_gossip.user.last_name %><br/>
        <u>Ville :</u> <%= @one_gossip.user.city.name %> <br/><br/>

        <u>Page Auteur :</u> <%= link_to "Cliques ici", user_path(@one_gossip.user.id) %><br/>
        <u>Page Ville :</u> <%= link_to "Cliques ici", city_path(@one_gossip.user.city_id) %><br/><br/>


        <u>Titre du potin :</u> <%= @one_gossip.title %><br/><br/>
        <u>Date de création :</u> <%= @one_gossip.created_at %><br/>
        <u>Date de la dernière mise-à-jour :</u> <%= @one_gossip.updated_at %><br/><br/>
        <u>Potin :</u><br/> <%= @one_gossip.content %><br/><br/>
      </p>
    </div>

    <div>
      <% if current_user.id == Gossip.find(params[:id].to_i).user.id %>
        <p>
          <u>Editer le potin :</u> <%= link_to "Cliques ici", edit_gossip_path(params[:id]) %><br/>
          <%= button_to "Supprimer ce potin", gossip_path(@one_gossip.id), method: :delete %>
           </tr>
        </p>
      <% end %>
    </div>

    <div>
      <p>
        <h3> Tags : </h3>
        <% if @one_gossip.tags != [] %>
          <b> Voici tous les tags associés à ce potin : </b><br>
            <% @one_gossip.tags.each do |tag| %>
              <%= tag.title %>
              <br>
            <% end %>
          </p>
        <% else %>
          <b> Aucun tag pour ce potin à date. </b>
        <% end %>
      </p>
    </div>

    <div>
      <p>
        <h3> Likes : </h3>

        <% if current_user.likes.include?(Like.find_by(imageable_type:"Gossip", imageable_id:params[:id], user_id:current_user.id)) == true %>

          <%= button_to "Supprimer un pouce", like_path(Like.find_by(imageable_type:"Gossip", imageable_id:params[:id], user_id:current_user.id).id), method: :delete %>

        <% else %>
          <%= button_to "Ajouter un pouce", likes_path(imageable_type:"Gossip", imageable_id:params[:id]), method: :post %>
        <% end %>

        <% if @one_gossip.likes != [] %>
          <b> Il y a <%= @one_gossip.likes.count %> like(s) pour ce potin ! </b><br>
        <% else %>
          <b> Aucun like pour ce potin à date. </b>
        <% end %>
      </p>
    </div>

    <div>
      <p>
        <h3> Commentaires : </h3>
        <% if @one_gossip.comments != [] %>
          <b> Voici tous les commentaires associés à ce potin : </b>
            <% @one_gossip.comments.sort_by{|comment| comment.updated_at}.reverse.each do |comment| %>
              <div class="card">
                <h5 class="card-header">Auteur :</u> <%= comment.user.first_name %> <%= comment.user.last_name %></h5>
                <div class="card-body">
                  <h5 class="card-title">Commentaire : <%= comment.content %></h5>
                  <u>Editer le commentaire :</u> <%= link_to "Cliques ici", edit_gossip_comment_path(@one_gossip.id,comment.id) %><br></br>
                  <%= button_to "Supprimer ce commentaire", gossip_comment_path(@one_gossip.id,comment.id), method: :delete %>

                  <div>
                    <p>
                      <% if comment.likes != [] %>
                        <b> Il y a <%= comment.likes.count %> like(s) pour ce commentaire ! </b><br>
                      <% else %>
                        <b> Aucun like pour ce commentaire à date. </b>
                      <% end %>
                      <% if current_user.likes.include?(Like.find_by(imageable_type:"Comment", imageable_id:comment.id, user_id:current_user.id)) == true %>

                        <%= button_to "Supprimer un pouce sur le com", like_path(Like.find_by(imageable_type:"Comment", imageable_id:comment.id, user_id:current_user.id).id), method: :delete %>

                      <% else %>
                        <%= button_to "Ajouter un pouce sur le com", likes_path(imageable_type:"Comment", imageable_id:comment.id), method: :post %>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
              <br>
            <% end %>
          </p>
        <% else %>
          <b> Aucun commentaire pour ce potin à date. </b>
        <% end %>
      </p>
    </div>
          
    <div>
      <h3>Crée un commentaire !</h3><br />
            
      <div class="form-page__form">
        <%= form_with model: [ @one_gossip, @one_gossip.comments.build ] do |form| %>
        
          <%= form.label :content %>
          <%= form.text_area :content %>
          <br /> <br />
        
          <%= form.submit "Enregistrer de ton commentaire !" %> 
        <% end %>
      </div><br /> <br />
    </div>      
  </body>
</html>