config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/welcome/contact', to: 'welcome#contact'
  get '/welcome/team', to: 'welcome#team'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  resources :gossips do
    resources :comments
  end

  resources :likes, only: [:index, :new, :create, :destroy]

end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :users
  has_many :gossips, through: :users
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @all_cities = City.all
  end

  def show
    @one_city = City.find(params[:id].to_i)
  end 

  def new
  end

  def create
  end 

  def edit 
  end 

  def update
  end 

  def destroy
  end 
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/cities/show.html.erb
<h3>Page dédiée à la ville n°<%= params[:id]%></h3><br>
<p>
  <u>Nom :</u> <%= @one_city.name %><br/><br/>

  <p>Voici la liste des potins actuellement disponibles sur notre plateforme pour cette ville :</p><br>

 
  <% @one_city.gossips.each do |gossip| %>
    <div class="card">
      <h5 class="card-header">Titre du potin :</u> <%= gossip.title %></h5>
      <div class="card-body">
        <h5 class="card-title">Auteur : <%= gossip.user.first_name %></h5>
        <a class="btn btn-primary" <%= link_to "Lire le potin !", gossip_path(gossip.id) %></a>
      </div>
    </div>
    <br>
  <% end %>
</p>