config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/welcome/contact', to: 'welcome#contact'
  get '/welcome/team', to: 'welcome#team'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  resources :gossips do
    resources :comments
  end

  resources :likes, only: [:index, :new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :user_id, presence: true
  validates :gossip_id, presence: true

  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :imageable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: { in: 3..14 }
  validates :content, presence: true, uniqueness: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :join_tag_gossips
  has_many :comments
  has_many :likes, as: :imageable
  has_many :tags, through: :join_tag_gossips
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
  validates :gossip_id, presence: true
  validates :tag_id, presence: true
  
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  validates :imageable_id, presence: true
  validates :imageable_type, presence: true
  
  belongs_to :imageable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :recipient_id, presence: true
  validates :sender_id, presence: true

  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
  has_many :users, through: :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city_id, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :login, presence: true, uniqueness:true

  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :tags, through: :gossips
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @all_cities = City.all
  end

  def show
    @one_city = City.find(params[:id].to_i)
  end 

  def new
  end

  def create
  end 

  def edit 
  end 

  def update
  end 

  def destroy
  end 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def new 
  end 

  def create
    @like = Like.create(imageable_type:params[:imageable_type],
    imageable_id:params[:imageable_id], user_id:current_user.id)
    if imageable_type="Gossip"
      redirect_to gossip_path(@like.imageable.id)
    else 
      redirect_to gossip_path(Gossip.find_by(@like.imageable.gossip.id))
    end 
  end 

  def destroy 
    @like = Like.find(params[:id])
    @like.delete

    if imageable_type="Gossip"
      puts "o"*60
      redirect_to gossip_path(@like.imageable.id)
    else 
      puts "Z"*60
      redirect_to gossip_path(Gossip.find_by(@like.imageable.gossip.id))
    end 
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @all_users = User.all
  end

  def show
    @one_user = User.find(params[:id])
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name:user_params["first_name"], last_name:user_params["last_name"], description:user_params["description"], email:user_params["email"], age:user_params["age"], login:user_params["login"], password:user_params["password"])
    
    cities_aray = City.all.map{|city|city.name.downcase}.to_a
    city_id = ""

    if cities_aray.include?(user_params["city"].downcase) == true 
      city_id = City.find_by(name:user_params["city"]).id
    else 
      new_city = City.create(name:user_params["city"])
      city_id = new_city.id.to_i
    end 

    @user.city_id = city_id

    if @user.save 
      session[:user_id] = @user.id
      redirect_to gossips_path(success_login:true)
      #redirect_to user_path(@user.id,success_user_create:true)
    else
      render 'new'
    end
  end 

  def edit 
  end 

  def update
  end 

  def destroy
  end 

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :login, :password, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet", href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" >

    <title>BetterGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbo="false" >
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" <%= link_to "Home", gossips_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Team", welcome_team_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Contact", welcome_contact_path %></a>
          </li>

          <% if current_user == nil %>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Connexion", new_session_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Créer un compte", new_user_path %></a>
            </li>
          <% else %>
            <li class="nav-item">
              <%= form_tag session_path(session.id), method: :delete do %>
                <%= submit_tag "Se déconnecter" %>
              <% end %>
            </li>
            <% end %>
          
        </ul>
      </div>
    </nav>
    <br>
    <%= yield %>
  </body>
</html>